Track/matcha
UCSDTESC/tesc.ucsd.edu pull request #48
Opened 2020-10-13 19:10 UTC by efeichen

2020-10-13 19:11 UTC, efeichen commented
@subhankar-panda do you think I should do the squash commit thing for this one?

2020-10-13 22:07 UTC, lisalluo requested changes
holy cow this looks amazing. you and your team did great. i think a few changes involving the uncertain parts of the event need to be made before it goes live so we dont have people getting confused or emailing us all the time

2020-10-13 22:07 UTC, lisalluo commented on src/pages/MatchaPage/index.js
> +                        <h1 className="matcha-hero__title">matcha</h1>
are you able to center the text when the screen is smaller?

2020-10-13 22:09 UTC, lisalluo commented
oops idk how to reply to comments but please do a squash thing when everything is resolved so we reduce the number of commits in our log

2020-10-19 06:49 UTC, efeichen commented on src/pages/MatchaPage/data/MatchaFaq.js
> +            'Follow our Facebook event page to stay up to date with Matcha.',
I can put the url in there but I don't think I can do an anchor `<a href="...">FB page</a>` since you know this is just text :((

2020-10-19 06:55 UTC, efeichen commented on src/pages/MatchaPage/index.js
> +                        <h1 className="matcha-hero__title">matcha</h1>
Ya they are once the screen is shrinked below 768px

2020-10-19 07:42 UTC, efeichen commented
Lol I tried to squash following some tutorials but I ended up just rebasing and merging and making more commits... I'm suppose to squash when I merge this on GitHub (there's a button for that apparently) so lmk when you think this is ready to go @lisalluo

2020-10-19 07:47 UTC, subhankar-panda commented on src/pages/MatchaPage/data/MatchaFaq.js
> +            'Follow our Facebook event page to stay up to date with Matcha.',
You can! Just import React at the top of the file and the JSX will get transpiled to `React.createClass` because it's a .jsx file :)

2020-10-19 18:21 UTC, lisalluo commented on src/pages/MatchaPage/index.js
> +                        <h1 className="matcha-hero__title">matcha</h1>
hmm it looks a little offcenter on some phones. maybe its overflowing? but rn its more important to get this website up, so this can be fixed (or not fixed) later

2020-10-19 18:23 UTC, lisalluo approved these changes
woohoo!! nice job :)

2020-10-19 18:24 UTC, lisalluo commented
> Lol I tried to squash following some tutorials but I ended up just rebasing and merging and making more commits... I'm suppose to squash when I merge this on GitHub (there's a button for that apparently) so lmk when you think this is ready to go @lisalluo

LOL yeah ill let you do the honors of merging :) just be sure to do the squash option on github

2020-10-19 18:29 UTC, lisalluo requested changes

2020-10-19 18:29 UTC, lisalluo commented on src/pages/MatchaPage/index.js
> +                            career fair at UCSD. Open exclusively to UCSD
career conference ;)

2020-10-19 18:29 UTC, lisalluo commented on src/pages/MatchaPage/data/MatchaFaq.js
> +            'Matcha is our first ever fully virtual career fair. It will be on October 22 from 9am-4pm',
career conference ;) and missing a period

2020-10-19 18:29 UTC, lisalluo commented on src/pages/MatchaPage/data/MatchaFaq.js
> +        question: 'How do I register for a ticket?',
comment this out for now too

2020-10-19 18:29 UTC, lisalluo commented on src/pages/MatchaPage/data/MatchaFaq.js
> +        answer:
can you comment this out too until we get an updated blurb?

2020-10-19 18:41 UTC, lisalluo approved these changes
YAYAY

2020-10-19 18:43 UTC, merged