Add council faq page
UCSDTESC/tesc.ucsd.edu pull request #64
Opened 2021-03-21 22:19 UTC by eliasfang

2021-03-22 02:32 UTC, efeichen reviewed
Overall looks good! Two small changes:

1. Can you make the question (the bolded text) of each question-answer pair bigger and add a big of margin between it and the answer paragraph?
2. Can you move the FAQ into a js file and place it in the data folder? I think that'll help with managing the FAQ (separate the data from the view). To add links instead of plain strings in the JS file, you can import React and write JSX snippets (checkout other data files for examples).

Lmk if you have any questions. Thank you!!

2021-03-23 04:06 UTC, efeichen commented on src/data/FAQData.js
> +const FAQData = [
FAQData is an array of just 1 object so it can just be an object by itself (aka. you don't need the brackets)

2021-03-23 04:08 UTC, efeichen commented on src/data/FAQData.js
> +                answer: [
`answer` is also an array when it should just be just JSX, I believe you can remove the brackets also and it should work. If not, put parenthesis around the JSX.

2021-03-23 04:11 UTC, efeichen requested changes
Almost there! Looks like you referenced the `FinanceReqs.js` file which tbh doesn't have the best data representation (it's a bit too complicated).

2021-03-23 04:11 UTC, efeichen commented on src/pages/FAQPage/components/FAQBlurb.js
> +            {FAQData.map((d, i) => (
Since we are changing the structure of the data file, these map calls need to be changed or removed as well.

2021-03-23 04:11 UTC, efeichen commented on src/pages/FAQPage/components/FAQSets.js
> +                            <div className="faq__question mt-4 mb-2 text-left">
make sure to add a `key` prop or else React will complain

2021-03-23 04:12 UTC, efeichen requested changes

2021-03-23 04:12 UTC, efeichen commented on src/data/FAQData.js
> +const FAQData = [
FAQData is an array of just 1 object so it can just be an object by itself (aka. you don't need the brackets)

2021-03-23 04:12 UTC, efeichen commented on src/data/FAQData.js
> +                answer: [
`answer` is also an array when it should just be just JSX, I believe you can remove the brackets also and it should work. If not, put parenthesis around the JSX.

2021-03-23 19:07 UTC, eliasfang commented on src/pages/FAQPage/components/FAQSets.js
> +                            <div className="faq__question mt-4 mb-2 text-left">
Added

2021-03-23 19:10 UTC, eliasfang commented on src/data/FAQData.js
> +const FAQData = [
Actually, for this one I have multiple objects {} so I think I do need the brackets right?

2021-03-23 19:13 UTC, eliasfang commented on src/data/FAQData.js
> +                answer: [
Changed

2021-03-23 19:23 UTC, efeichen approved these changes

2021-03-23 19:25 UTC, merged